### ISSUE TITLE
could you share the pretrained model for test？

### ISSUE THREAD

**Issue by ForrestPi** [Walter0807/mocanet.pytorch#1]
Hi, could you share the pretrained model for test？

**Comment by vnghia** [comment]
Hi, You could find the `checkpoints` [here](https://drive.google.com/file/d/1lpIA-ECaPA08F5mlA1UyVEGE43-apm0T/view?usp=share_link).

**Comment by Walter0807** [comment]
Thank you @vnghia !

**Comment by QUTGXX** [comment]
Sorry, the file you have requested does not exist. Can u give us a new download link? @vnghia

**Comment by vnghia** [comment]
Sure please find it here: https://www.kaggle.com/code/vnghia/mocanet in the output section the out.zip

**Comment by QUTGXX** [comment]
> Sure please find it here: https://www.kaggle.com/code/vnghia/mocanet in the output section the out.zip

Thanks a lot, by the way, I want to know when we run the infer_pair.py, should we rescale the source and target's pose key-points to (-1,1)?
