### ISSUE TITLE
Module 'Autoencoder3fCanonical' has no attribute 'reconstruct'

### ISSUE THREAD

**Issue by vnghia** [Walter0807/mocanet.pytorch#3]
Hi, I am trying to convert the trained model to TorchScript. However, it seems that this function does not defined anywhere. https://github.com/Walter0807/mocanet.pytorch/blob/6aaf1d6d6eb6f1f4c69ea3b4b7a55c172008de50/lib/network.py#L389

Could you take a look at this ?

Thank you very much !

**Comment by Walter0807** [comment]
Seems like this function is not called. How about change this line to
```python
pass
```

**Comment by vnghia** [comment]
Thank you I ended up doing some modifications here https://github.com/vnghia/mocanet.pytorch/tree/main and I could finally export the mocanet with mixamo into a TorchScript model for loading into C++

The model can be found [here](https://drive.google.com/file/d/1jUFLZHPo5OwM91hotty5wjOhjphT9596/view?usp=share_link)
