### ISSUE TITLE
The right input to feed into model 

### ISSUE THREAD

**Issue by vnghia** [Walter0807/mocanet.pytorch#4]
Hello, I would like to ask what is the right input to feed into the model. When extract the skeleton from densepose, the result is in the range of `x in [0, width]` and `y in [0, height]`. But the `npy` in the data section has range from `[-2, 2]`. Could you provide some instructions (scaling ratio, translation, etc ) how to transform into the right range to feed in the model ?

Thank you very much !

**Comment by Walter0807** [comment]
Hi, you can normalize the motion by scaling and translation to the range [-2, 2]. For example, https://github.com/yzhq97/transmomo.pytorch/blob/master/lib/util/motion.py#L108.
