### ISSUE TITLE
Meet some questions while run calculate_metrics_3d.py

### ISSUE THREAD

**Issue by zzzbbs** [Walter0807/mocanet.pytorch#5]
After training, I want to use 'calculate_metrics_3d.py' to directly evaluate the trained model or transform .npy file into video file. I meet the following wrong, it seems that the 'visualize' module is not included in the 'scripts' module.   

command:
`python scripts/exp/calculate_metrics_3d.py --in_dir ./test/ --render`

result:
`Traceback (most recent call last):
  File "scripts/exp/calculate_metrics_3d.py", line 7, in <module>
    from scripts.visualize.visualize_keypoints_npy import render_preview
ModuleNotFoundError: No module named 'scripts.visualize'`

**Comment by Walter0807** [comment]
Hi, to evaluate the trained model you can turn off the --render flag. Hope that helps.

**Comment by zzzbbs** [comment]
> Hi, to evaluate the trained model you can turn off the --render flag. Hope that helps.
Thank you for your reply! Besides directly evaluating the trained mdel, I also want to transform .npy file into video file or reconstructed 3D skeleton data. So I turn on the --render flag. Is there other ways to extract 3d skeleton data from .npy file?

**Comment by zzzbbs** [comment]
> Hi, to evaluate the trained model you can turn off the --render flag. Hope that helps.

Thank you for your reply! Besides directly evaluating the trained mdel, I also want to transform .npy file into video file or reconstructed 3D skeleton data. So I turn on the --render flag. Is there other ways to extract 3d skeleton data from .npy file?
