### ISSUE TITLE
Some questions about infering reconstructed 3D pose from in-the-wild video.

### ISSUE THREAD

**Issue by zzzbbs** [Walter0807/mocanet.pytorch#6]
Hi Walter0807,sorry for the bother. Thank you for releasing the code!
 I trained mocanet model by `python train.py --config configs/mocanet.yaml`.
 After 'test.py', I could get a series of .npy(2D & 3D position) which from ANDROMEDA to PUMPKINHULK.
 The questions are as follows:
 1. Could I directly used the pretrained model to infer motion、body、view from a single in-the-wild video?
 2. If not, what is the requirement of in-the wild video? Should it come from a same demonstrator body structure?
 3. If yes, I want to use the canonical structure to predict 3D position, could this canonical structure be general to in-the-wild video?

**Comment by Walter0807** [comment]
1. Yes, you will need to extract 2D skeletons from your videos with tools like OpenPose, AlphaPose, Detectron, etc.
2. -
3. I don't quite understand your question ('use the canonical structure to predict 3D position'). If you mean generalization, generally it could work if the motion is not too far away from the training set distribution.

**Comment by zzzbbs** [comment]
> 
Thanks for your quick reply!
The third question is about getting a reconstruted 3D position or 2D position after structure canonication and view canonication from In-the-wild video. 
I want to use the pretrained `canonical_structure_00200000.pt` as body. 
And canonical_structure is trained after 'mixamo' dataset, So I ask about its generalization to other in-the-wild video.

**Comment by Walter0807** [comment]
Yes, the canonical structure is learned on mixamo. Generally, we don't care about the scale of the canonical structure too much, we just want it to be constant for disentanglement. Therefore, using the canonical_structure learned on mixamo is OK. You can also train on in-the-wild videos if you want.

**Comment by zzzbbs** [comment]
> 
Thank you for answering above questions!!! Sorry for the one last question.
Additionaly,I noticed that you mentioned the 'training set distribution' above. 
Does it mean that if I want to reconstruct some motion out of mixamo dataset, I need to add or build some 2D skeleton data for the newly motion? 
For example, solo_dance has some motions out of mixamo dataset, I need to add in my training set.

**Comment by Walter0807** [comment]
I think you don't need to retrain. For in-the-wild videos, models trained on SoloDancer might perform better. You can try out them both.

**Comment by zzzbbs** [comment]
Thank you for answering my all questions! Happy new year!
